apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testweb
  name: testweb
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30803
  selector:
    app: testweb
status:
  loadBalancer: {}