apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: TestWeb
  name: TestWeb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TestWeb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: TestWeb
    spec:
      containers:
      - image: ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_VERSION}
        name: testingapi
        resources: {}
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"