apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testweb
  name: testweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testweb
  template:
    metadata:
      labels:
        app: testweb
    spec:
      containers:
      - image: ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_VERSION}
        name: testweb
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: jenkins-credentials