apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: TestWeb
  name: TestWeb
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30809
  selector:
    app: TestWeb
status:
  loadBalancer: {}